### ISSUE TITLE
BUG: picard + salmon + samtools: SAM validation error due to unmapped reads

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/snakemake-workflows#166]
**Describe the bug**
Salmon pipes to `samtools view`, which pipes to the sorter of choice. Picard then marks duplicates, but throws the following error:

> Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 110, Read name NS500173:496:H52JJBGXB:3:22506:6852:2808, Not primary alignment flag should not be set for unmapped read.

**Dirty solution**
Unmapped reads [could be discarded beforehand](https://www.biostars.org/p/56246/), as these are pseudobams.

**Comment by Maarten-vd-Sande** [comment]
Does this still happen btw? Why does it even set this flag to begin with?

**Comment by siebrenf** [comment]
I haven't had time to check the Salmon workflow further. I would like to fix this issue, and streamline the RNA-seq pipeline with aligners other than STAR too.

**Comment by siebrenf** [comment]
This issue can be dropped as Salmon will be taken out of the list of aligners. 

Pseudobams may be re-implemented in the future, but seem unnecessary at the moment. Feel free to reopen if needed!
