### ISSUE TITLE
FR: Multi-genome assembly hubs

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/snakemake-workflows#172]
daler/Trackhub can create a hub, does not create additional files.
Gaius-Augustus/MakeHub can create an assembly hub, but only for one genome.

**Comment by Maarten-vd-Sande** [comment]
Are you working on this? Shall I take over?

**Comment by Maarten-vd-Sande** [comment]
@siebrenf this can be closed right? It's working (good enough).

**Comment by siebrenf** [comment]
I want to have a look at the last few things still. It may be a nice pre-christmass project :)
