### ISSUE TITLE
FR: wildcard fqext with constraints

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/snakemake-workflows#192]
**Is your feature request related to a problem? Please describe.**
selecting R1/pass1 is annoying. 

**Describe the solution you'd like**
Let's try to make it a wildcard with constraints from a list (containing these two as defaults), and allow users to set others.

**(optional) Additional context**
In config.smk, the any_given and global wildcard constraints give us a setup to do this.

**Comment by Maarten-vd-Sande** [comment]
Yes would be nice! How does this work with downloaded files? How would it decide what to call those?

**Comment by siebrenf** [comment]
Pick the last option from each list. That way the user added extensions are selected if given, and otherwise either of the pre-defined ones (I guess _pass_1 and _pass_2).

**Comment by siebrenf** [comment]
This feature wasn't implementable as suggested due to the constraints on wildcards in Snakemake. 
-The program requires all wildcards to be present in all outputs, which doesn't allow wildcards for fqext1 and fqext2 in the same rule. 
-Dictionaries do not work either, as their key (wildcard.samples) is evaluated after expanding the rule in/output.
-Finally, functions are not allowed in a rule output.

An alternative solution has been added: if a file can be found in the fastq_dir with a matching sample name, but a mismatched fqext, a temporary symlink will be created and used for the pipeline. 

fqext1 and fqext2 will remain options in the config, as they determine the default extension Snakemake will use (and they pop up in the QC files).

Changes can be found in branch Powerwolf :metal:
