### ISSUE TITLE
BUG: rna-seq > trackhub

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/snakemake-workflows#209]
**Describe the bug**
`'InputFiles' object has no attribute 'twobits'`

**To Reproduce**
run the rna-seq pipeline

**Comment by Maarten-vd-Sande** [comment]
https://github.com/vanheeringen-lab/snakemake-workflows/blob/0990c6280fbe6f3d502f8dbd7d2f95a91d167911/rules/trackhub.smk#L298

Probably changing that call would solve everything:
`if any(assembly in twobit for twobit in input.getattr('twobits', []):`
