### ISSUE TITLE
base pair shift

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#22]
We could add for completeness base pair shift
https://www.biostars.org/p/187204/#187206

**Comment by Maarten-vd-Sande** [comment]
Seems easy/straightforward enough to implement. However Genrich already has this pre-built in

**Comment by siebrenf** [comment]
[Deeptool alignmentSieve](https://deeptools.readthedocs.io/en/develop/content/tools/alignmentSieve.html) (which Maarten told me about), can do this, quality trimming, and accepts a blacklist.bed or .gtf.

It can even be used to add an optional filter for unique reads!

The input needs to be indexed (thus sorted). The output needs to sorted again (at least with multiple cores assigned).

**Comment by Maarten-vd-Sande** [comment]
So this index + sorting is actually quite a problem, since that makes alignmentsieve impossible for queryname sorted stuff (e.g. genrich + snapATAC). 

I think I will hack some awk together that filters blacklist and tn5 offset at the same time, and can be added in between the alignment and sort. Might add mitochondrial read removal as well. Having all this piped from `alignment | tn5 & mito & blacklist | sort` will save a lot of unneccesary saving and loading of files, and might save quite some load on our HDDs, and thus our mini-cluster! :smile:
