### ISSUE TITLE
BUG: bad tests

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#240]
@siebrenf 
Since we cannot get the tests to work how we want, and this is annoying with the conda bot. 

I propose I turn off the bot for now and just make some toy data and we run every test always. Probably makes the tests faster as well. Once this works the bot can be turned on again.

**Comment by siebrenf** [comment]
We can turn off or ignore the bot's PRs. Both are fine by me.

Toy data is already in place in all situations except two:
-downloading test: 1 small SE and PE sample is downloaded, as well as fr3
-atac-seq test: this uses the data downloaded in downloading test (toy data causes an error in rule featureCount)

This means that the downloading requirement is already minimized. Making toy data for the ATAC-seq test would speed up that test too though!

**Comment by Maarten-vd-Sande** [comment]
I didn't notice alignment has tests as well. I'll take a look tomorrow, would be great if we can get the tests at least under 10 mins.

**Comment by siebrenf** [comment]
You wrote the originals xD

Options to speed-up alignment-test:
-We could make a Snakefile that does not require dedups. That way, deduplication has to run only for one aligner, and the other 3 could just align and be done with it.
-Additionally, we could save the tinydata indexes and assume that get_index rules are stable (enough).

Neither of these options are really good. In fact, we should add more tests with the different sorters!

What might really speed up the process is if we can run tests in parallel. Tax your PC some more!

**Comment by Maarten-vd-Sande** [comment]
Yeah I meant the tinydata for the alignment. :angel: 

Another option might be to not lock the directory, but I'm not entirely sure if that works. I'll take a look (maybe) before Xmas :smile:

**Comment by siebrenf** [comment]
Parallel tests are in place in #245 where possible. It is indeed using unlocked directories!

Two further improvements can be made:
* Tinydata that can be run by the ATAC-seq pipeline.
* fixing the logic to skip testing steps that do not need to be rerun.
