### ISSUE TITLE
Trackhub stuff

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/snakemake-workflows#256]
When running the RNAseq pipeline with my own fastq files and genome, the trackhub rule crashes:

```
rule trackhub:
    input: <TBD>
    output: /home/jsmits/Epithelial_fate_KC_LSC/RNA/trackhub
    log: /home/jsmits/Epithelial_fate_KC_LSC/RNA/log/trackhub/trackhub.log
    jobid: 4
    benchmark: /home/jsmits/Epithelial_fate_KC_LSC/RNA/benchmark/trackhub/trackhub.benchmark.txt
```

It seems to fail to generate the proper input, and therefore crashes a little time later:

```
INFO:snakemake.logging:[Tue Feb 25 12:08:57 2020]
Error in rule trackhub:
ERROR:snakemake.logging:Error in rule trackhub:
    jobid: 0
ERROR:snakemake.logging:    jobid: 0
    output: /home/jsmits/Epithelial_fate_KC_LSC/RNA/trackhub
ERROR:snakemake.logging:    output: /home/jsmits/Epithelial_fate_KC_LSC/RNA/trackhub
    log: /home/jsmits/Epithelial_fate_KC_LSC/RNA/log/trackhub/trackhub.log (check log file(s) for error message)
ERROR:snakemake.logging:    log: /home/jsmits/Epithelial_fate_KC_LSC/RNA/log/trackhub/trackhub.log (check log file(s) for error message)
```

```
ERROR:snakemake.logging:
RuleException:
AttributeError in line 501 of /home/jsmits/snakemake-workflows/rules/trackhub.smk:
'InputFiles' object has no attribute 'twobits'
  File "/home/jsmits/snakemake-workflows/rules/trackhub.smk", line 501, in __rule_trackhub
  File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/concurrent/futures/thread.py", line 56, in run
ERROR:snakemake.logging:RuleException:
AttributeError in line 501 of /home/jsmits/snakemake-workflows/rules/trackhub.smk:
'InputFiles' object has no attribute 'twobits'
  File "/home/jsmits/snakemake-workflows/rules/trackhub.smk", line 501, in __rule_trackhub
  File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
ERROR:snakemake.logging:Exiting because a job execution failed. Look above for error message
```

**Comment by Maarten-vd-Sande** [comment]
Are you on master branch?

**Comment by Maarten-vd-Sande** [comment]
and up to date?

**Comment by Maarten-vd-Sande** [comment]
```
git checkout master
git pull
```

**Comment by Maarten-vd-Sande** [comment]
pinging @siebrenf since he worked on it last and might have an idea

**Comment by JGASmits** [comment]
M       workflows/atac_seq/config.yaml
M       workflows/atac_seq/samples.tsv
M       workflows/rna_seq/config.yaml
M       workflows/rna_seq/samples.tsv
Already on 'master'
Your branch is up-to-date with 'origin/master'.

**Comment by JGASmits** [comment]
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 12), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (20/20), done.
From https://github.com/vanheeringen-lab/snakemake-workflows
 * [new branch]      Maarten-vd-Sande-#253 -> origin/Maarten-vd-Sande-#253
 * [new branch]      id2sra_fix            -> origin/id2sra_fix
Already up-to-date.

**Comment by siebrenf** [comment]
It's that buggy checkpoint mechanic again. It doesn't evaluate the checkpoint (i guess because it didn't need to update any step before this).

Untill it's fixed, I think this may hack it out: in trackhub.smk, change
`        f = os.path.splitext(checkpoints.get_genome.get(assembly=assembly).output[0])[0]
        gtf = any([os.path.isfile(f+".annotation.gtf"), os.path.isfile(f+".gtf")])`

into

`gtf = True`

It will assume you have a GTF file, which is correct for RNA-seq anyway.

**Comment by JGASmits** [comment]
I quickly discussed it with Siebren yesterday late in the afternoon, but also put it here so the error is find-backable :)

**Comment by JGASmits** [comment]
Ill try the fix in the afternoon, thanks!

**Comment by Maarten-vd-Sande** [comment]
How is this passing our tests?!

**Comment by siebrenf** [comment]
I guess it works because it needs to run _some_ step that does update the checkpoint. I have yet to figure out the exact logic of the checkpoint (or at least this version of it)...
