### ISSUE TITLE
BUG: Better error when samples.tsv is malformed

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#260]
Now it's difficult for beginner users, and I've seen it happen many timtes.

**Comment by Maarten-vd-Sande** [comment]
I guess people were working in an old version. These checks seem quite elaborate already, and should catch plently.

**Comment by siebrenf** [comment]
some extra checks are added in configuration.smk of branch replicates.
The biggest issue (i think) is that the assert messages are drowned by the traceback.

we could set `sys.tracebacklimit = 0` at the start of configuration.smk, and set `sys.tracebacklimit = 1` at the end?

**Comment by Maarten-vd-Sande** [comment]
Isn't the message all the way at the bottom anyways? So that shouldn't matter?

**Comment by siebrenf** [comment]
It shouldn't. But reading errors can be challenging.

According to [this SO post](https://stackoverflow.com/questions/34245645/assert-without-the-traceback-in-python), `assert` shouldn't be used for these checks. That would explain why the message contains both traceback and message.

Either way, I'm OK leaving it as-is for now.

**Comment by Maarten-vd-Sande** [comment]
Yeah you should raise errors, but thats a lot of typing :angel:
