### ISSUE TITLE
FR: Broad and Narrow peak calling in Chip-seq workflow

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/snakemake-workflows#284]
I'm going to try out the Chipseq workflow (#flock yea super cool!), since it suports the descriptive_name, which is ideal since I'm downloading some data. However most of the called peaks I think I can toss, since the MACS2 options for broad and Narrow peakcalling will need to be differend.

It would be cool if we could include a type of peak collumn in the sample file, with the options 'broad' or 'narrow', which you could specify in the config file. 
Not sure if it is possible or yet what the exect options of MACS2 are in those curcomstances. But just an idea I dont want to forget.

Gr Jos

**Comment by Maarten-vd-Sande** [comment]
Not sure what you want, supporting broad peaks was already on the roadmap, but no real start was made for it.

Do you want to call broad and narrow peaks in the same experiment? Or just only call broad peaks? To call broad peaks you need to add the `--broad`flag in the `config.yaml`, but for now the problem is that will output a different file than is expected.

**Comment by Maarten-vd-Sande** [comment]
(at the moment broad peaks do not work with our pipeline)

**Comment by Maarten-vd-Sande** [comment]
+ what do you want out of an chip-seq pipeline like this? How would this work for the count table? What quality metrics do you expect?

**Comment by JGASmits** [comment]
I'd want to be able to include both broad chip data (H3k27ac), together with more narrow (H3K4me3, TF chips). For me the end product would be called peaks (or summits), together with the wiggle files. QC and counttable generation I'm doing downstream after mergins stuff here and there. However perhaps this is a bit to specific of a use case. :)
I'm in no rush however, and in the future will look more into what exactly I want to do on the differend types of data. So I could also come back to this once I have this more clear. :)

**Comment by Maarten-vd-Sande** [comment]
Ok after some thinking, I think this will be way to much of a hassle to maintain :angel:

Once broadpeak support is added I think you should just run the two things separately. Mixing multiple trackhubs is supported by ucsc anyways, and for the other stuff you would have to find a way to combine them, but that should be relatively easy.

**Comment by JGASmits** [comment]
Alright :)

**Comment by Maarten-vd-Sande** [comment]
We do still want broad peak support :)
