### ISSUE TITLE
BUG: weird conda/server behaviour?

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/snakemake-workflows#288]
I'm not sure why, it could be a server related issue. But after switching to the develop version and updating the snakemake-workflows env, i got  the next error multiple times when trying to making the gimme.yaml environment for the chipseq workflow:

_> CondaVerificationError: The package for scipy located at /home/jsmits/anaconda3/envs/snakemake-workflows/pkgs/scipy-1.4.1-py36h921218d_0
> appears to be corrupted. The path 'lib/python3.6/site-packages/scipy/__pycache__/__init__.cpython-36.pyc'
> specified in the package manifest cannot be found.
... etc
>_ 

Since something looked corrupted I removed the snakemake-workflow env and regenerated it fresh and new from the develop .yml file. However when I then tried to run it I ran into a differend error at exactly the same step: 

_> CreateCondaEnvironmentException:
> Could not create conda environment from /home/jsmits/snakemake-workflows/rules/../envs/gimme.yaml:
> Collecting package metadata (repodata.json): ...working... failed

> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 107, in touch
>         mkdir_p_sudo_safe(dirpath)
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
>         os.mkdir(path)
>     FileExistsError: [Errno 17] File exists: '/home/jsmits/anaconda3/envs/snakemake-workflows/pkgs'
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/core/subdir_data.py", line 189, in _load
>         mtime = getmtime(self.cache_path_json)
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/core/subdir_data.py", line 157, in cache_path_json
>         return self.cache_path_base + '.json'
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/core/subdir_data.py", line 148, in cache_path_base
>         create_cache_dir(),
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/core/subdir_data.py", line 649, in create_cache_dir
>         cache_dir = join(PackageCacheData.first_writable(context.pkgs_dirs).pkgs_dir, 'cache')
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 160, in first_writable
>         created = create_package_cache_directory(package_cache.pkgs_dir)
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 435, in create_package_cache_directory
>         touch(join(pkgs_dir, PACKAGE_CACHE_MAGIC_FILE), mkdir=True, sudo_safe=sudo_safe)
>       File "/home/jsmits/anaconda3/envs/snakemake-workflows/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 125, in touch
>         raise NotWritableError(path, e.errno, caused_by=e)
>     conda.exceptions.NotWritableError: The current user does not have write permissions to a required path.
>       path: /home/jsmits/anaconda3/envs/snakemake-workflows/pkgs/urls.txt
>       uid: 14752
>       gid: 14752
> 
>     If you feel that permissions on this path are set incorrectly, you can manually
>     change them by executing
> 
>       $ sudo chown 14752:14752 /home/jsmits/anaconda3/envs/snakemake-workflows/pkgs/urls.txt
> 
>     In general, it's not advisable to use 'sudo conda'.
> 
>     During handling of the above exception, another exception occurred:
>     etc..._

Which was very weird, i tried multiple things, and eventually updating the version of python in the environment seemed to have worked

_

> The following packages will be UPDATED:
> 
>   python                pkgs/main::python-3.6.10-h191fe78_1 --> conda-forge::python-3.6.10-h9d8adfe_1009_cpython
>   readline               pkgs/main::readline-7.0-h7b6447c_5 --> conda-forge::readline-8.0-hf8c457e_0
> 
> The following packages will be SUPERSEDED by a higher-priority channel:
> 
>   ncurses                 pkgs/main::ncurses-6.2-he6710b0_0 --> conda-forge::ncurses-6.1-hf484d3e_1002_

_

Now it succesfully generated all conda environments and is running the pipeline. However I'm not sure if it is a weird server flockup or if the updating of python really did something and that is the thing that fixed it. Instead of forgetting this while somebody else might run into it, I thought I'd make it an isue so you guys also know if something similar pops up with somebody else.

If an issue is not the right place for this kind of thing or not needed, just let me know!

Gr Jos

**Comment by Maarten-vd-Sande** [comment]
Unfortunately this is a conda-related thing. I am not sure how this happens, but i had it before myself as well. I think (hope) you were just really unlucky to get these rare errors twice in a row.

**Comment by JGASmits** [comment]
Alright then I'll close it :)

**Comment by Maarten-vd-Sande** [comment]
Just for future reference:
1. removing the `.snakemake` directory should solve this issue.
2. if that does not resolve it try removing both the `snakemake-workflows` environment and again the `.snakemake` directory.
