### ISSUE TITLE
 rule alignmentsieve I/O bottleneck?

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/snakemake-workflows#303]
I noticed when running multiple alignmentsieve rules, that the per thread usage would drop down to neglectable CPU usgage. The pipeline didnt really seem to make any progress.

If i ran Rita's: 'usage' script, it would give an warning to emidiately stop heavy Input/Ouptut intensive workloads. Is it possible that with multiple alignmentsieve rules the IO of the server is bottlenecked?

Its furthermore weird, that if i start a pipline with only 4 cores (-j 4), many more processes are started (see th atac snakemake processes in the bellow attached screenshots)
<img width="1938" alt="multiple cores" src="https://user-images.githubusercontent.com/47240368/78219496-ec48f000-74bf-11ea-9911-5f55121a0624.png">

I dont know a lot about I/O but if I remember correctly it is one of the few things that can properly mess up the server witouth raising any warnings. 
  

Gr Jos

**Comment by JGASmits** [comment]
PS: I'm on the deeptools_qc branch, but will test if the same happens on develop in a bit.

**Comment by Maarten-vd-Sande** [comment]
It happens everywhere I guess

**Comment by Maarten-vd-Sande** [comment]
@siebrenf had this problem before with other deeptools functions. Deeptools makes a lot of temp files, and this is indeed very IO expensive. There is already a deeptools_limit resource we could just add to the other deeptools rules, so that's no problem. 

Do you know how many deeptools were you running in parallel?

**Comment by JGASmits** [comment]
It was still running with 4 alignmentsieve rules (which I guess are deeptools?) in parrallel. I have the feeling but its tricky to quantify that more parallel rules just increased IO waiting times.

**Comment by Maarten-vd-Sande** [comment]
A big part of this problem is just mb07 which we can not solve. It won't run more than 4 alignmentsieves in parallel at the moment. 

Hopefully the new server will be faster.
