### ISSUE TITLE
FR: Finalize scATAC

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#326]
TODO:
* annotation
* incorporate treps

**Comment by Maarten-vd-Sande** [comment]
@JGASmits I incorporated the "technical replicates" logic, and we will still need to do some general cleanups in the end. Take a look at samples.tsv for how to fill out the samples file. It unfortunately does not (yet) work with public data, since the barcodes are missing (I think):
`error: @get_barcode_cov_from_bam: barcode_list is empty!`

Take a look at the `config.yaml`, I left a question there regarding the defaults. Whether to have them in the snaptools or in the "general" config.

p.s. the possibilities are endless, but are there any specific qc-metrics cool for scATAC? UCSC also supports scBrowser. So this is also something to look at.

**Comment by JGASmits** [comment]
For the annotation I think i might write a small script to just generate the cell ID based on the primer locations for people from our lab (the location this is inputed is in snapATAC anyhow) and keep it out of the snakemake-workflows. :) 
I'm testing the fastq fix right now and will start writing the docs. 👍

**Comment by JGASmits** [comment]
I think I'll also might include the first SnapATAC QC file metricis in the pipeline. That way they are also included in the multiQC file, but ill see if I can get that to work. :)
