### ISSUE TITLE
Add resources (e.g. mem usage) to each rule

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#7]
Based on bechmark results?
https://github.com/vanheeringen-lab/snakemake-workflows/issues/5

**Comment by Maarten-vd-Sande** [comment]
Yes this is still relevant!

**Comment by siebrenf** [comment]
Added several resources for rules used in rna-seq #167 :

memory usage:
- salmon
- star
- samtools_sort
- mark_duplicates

other bottlenecks:
- deeptools=1 (doesn't run in parallel)
- parallel_downloads=1 (was already set by Maarten)

Values originated from benchmarks run on samples mapped to the human genome. 
Trimming rules and samtools_index had a negligible memory usage.
