### ISSUE TITLE
GSMs can contain multiple SRRs

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/snakemake-workflows#80]
example: [GSM352203](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM352203)

**Comment by Maarten-vd-Sande** [comment]
https://www.biostars.org/p/100325/

**Comment by siebrenf** [comment]
Closing this issue as the last change seems to be the correct solution.

**Comment by Maarten-vd-Sande** [comment]
When I am downloading GSM352203 it does not crash, however it seems to download only one of the 5 runs, and hence only dump this one.

**Comment by siebrenf** [comment]
Are you sure the runs are not concatenated?

**Comment by Maarten-vd-Sande** [comment]
Yes, the problem is with the wget fallback. Wget downloads all files each time for each id, and then seems to write them all to the same file

**Comment by Maarten-vd-Sande** [comment]
Okay the current implementation is faulty, in that SRA's shouldnt be concatenated I believe. GSM3141725 consists of 2 runs, if I download that one through our pipeline I get a fastq of 2.2Gigabyte, however the two runs are 2.1 and 4.1 gigabyte.

We should concatenate them after the dumping I believe
