### ISSUE TITLE
Implement automated tests with travis

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#84]
#14 related

**Comment by siebrenf** [comment]
potential example files

GSM1483770 Single-ended. 2 MB as fastq.gz
GSM352203 Single-ended. contains multiple SRRs. 44 MB as fastq.gz
ERR1397005 Paired-ended. No SRA available. 180 MB as fastq.gz
GSM919950 Paired-ended. 1.6 GB as fastq.gz

**Comment by Maarten-vd-Sande** [comment]
False sense of security implemented!
